import { StyleSheet } from 'react-native';

export const counterStyles = StyleSheet.create({
  statBox: {
    flex: 1,
    alignItems: 'flex-start',
    marginHorizontal: 24,
    padding: 8,
  },
  statLabel: {
    color: '#1e40af',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'left',
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  valueBox: {
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#1e40af',
    borderRadius: 12,
    width: 80,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  valueBoxExResource: {
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#f59e0b',
    borderRadius: 12,
    width: 80,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  valueText: {
    color: '#1e40af',
    fontSize: 32,
    fontWeight: 'bold',
  },
  valueTextExResource: {
    color: '#f59e0b',
    fontSize: 32,
    fontWeight: 'bold',
  },
  statLabelExResource: {
    color: '#f59e0b',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'left',
  },
  buttonContainer: {
    justifyContent: 'space-between',
    height: 80,
  },
  controlButton: {
    backgroundColor: '#1e40af',
    borderWidth: 2,
    borderColor: '#1e40af',
    borderRadius: 8,
    width: 40,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlButtonExResource: {
    backgroundColor: '#f59e0b',
    borderWidth: 2,
    borderColor: '#f59e0b',
    borderRadius: 8,
    width: 40,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
});
